reviewers:
  # The default reviewers
  defaults:
    - apps-team-1
    - growth-team
    - apps-team-2

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    growth-team:
      - olegoblomov
    apps-team-1:
      - SanCHEESE
      - kgolenkov
    apps-team-2:
      - Safariiii
      - Denver2003
      - H0xel

options:
  ignore_draft: true
  enable_group_assignment: false
  number_of_reviewers: 3
