name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  auto-request-review:
    name: Auto Assign Reviewers
    runs-on: ubuntu-latest
    steps:
      - name: Assign review based on files changes and/or groups the author belongs to
        uses: necojackarc/auto-request-review@v0.8.0
        with:
          token: ${{ secrets.PAT_FOR_AUTO_REQUEST_REVIEW }}
          config: .github/reviewers.yml # Config file location override
